### ISSUE TITLE
Thanks - and issue with setup

### ISSUE THREAD

**Issue by dgdosen** [basecamp/powprox#3]
Thanks for creating powprox! - 

I tried a plain vanilla setup with nginx installed via homebrew, and get an error running powprox:

```
Checking Nginx config…
nginx: [emerg] "user" directive is not allowed here in /usr/local/etc/nginx/servers/powprox.conf:2
nginx: configuration file /usr/local/etc/nginx/nginx.conf test failed
```

any help?

**Comment by jeremy** [comment]
Hi @dgdosen – you're welcome! Thanks for giving it a shot.

Could you verify that your homebrew nginx config ends with a toplevel `include servers/*;` directive:

```
$ tail -1 /usr/local/etc/nginx/nginx.conf
include servers/*;
```

And double check the `user` directive that powprox created:

```
$ head -2 /usr/local/etc/nginx/servers/powprox.conf 
# Run nginx worker as the current user instead of 'nobody'
user jeremy staff;
```

[Nginx accepts `user` at the top level](http://nginx.org/en/docs/ngx_core_module.html#user) (the "main" context), so that error suggests that the homebrew nginx config has its `include` directive elsewhere, perhaps within a `server` block.

**Comment by tomafro** [comment]
@jeremy My homebrew installed nginx has `include servers/*;` at the bottom (but inside) an `http` block

**Comment by jeremy** [comment]
Turns out the Homebrew formula recently changed the location of its `include servers/*;` directive which broke our included config. Worked around this by introducing a toplevel `include conf.d/*;' instead and including Powprox there.
